// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type HealthResp struct {
	Status string `json:"status"`
}

type DeleteBusinessObjectsReq struct {
	Id string `path:"id" validate:"required"`
}

type DeleteBusinessObjectsResp struct {
	Success bool `json:"success"`
}

type GenerateUnderstandingReq struct {
	Id string `path:"id" validate:"required"`
}

type GenerateUnderstandingResp struct {
	UnderstandStatus int8 `json:"understand_status"`
}

type FieldSemanticInfo struct {
	FormViewFieldId   string  `json:"form_view_field_id"`
	FieldBusinessName *string `json:"field_business_name"`
	FieldTechName     string  `json:"field_tech_name"`
	FieldType         string  `json:"field_type"`
	FieldRole         *int8   `json:"field_role"`
	FieldDescription  *string `json:"field_description"`
}

type GetBusinessObjectsReq struct {
	Id       string  `path:"id" validate:"required"`
	ObjectId *string `form:"object_id"`
	Keyword  *string `form:"keyword"`
}

type GetBusinessObjectsResp struct {
	List []BusinessObject `json:"list"`
}

type GetFieldsReq struct {
	Id             string  `path:"id" validate:"required"`
	Keyword        *string `form:"keyword"`
	OnlyIncomplete *bool   `form:"only_incomplete"`
}

type GetFieldsResp struct {
	CurrentVersion    int                 `json:"current_version"`
	TableBusinessName *string             `json:"table_business_name"`
	TableTechName     string              `json:"table_tech_name"`
	TableDescription  *string             `json:"table_description"`
	Fields            []FieldSemanticInfo `json:"fields"`
}

type GetStatusReq struct {
	Id string `path:"id" validate:"required"`
}

type GetStatusResp struct {
	UnderstandStatus int8 `json:"understand_status"`
}

type MoveAttributeReq struct {
	Id               string `path:"id" validate:"required"`
	AttributeId      string `json:"attribute_id" validate:"required"`
	TargetObjectUuid string `json:"target_object_uuid" validate:"required"`
}

type MoveAttributeResp struct {
	AttributeId      string `json:"attribute_id"`
	BusinessObjectId string `json:"business_object_id"`
}

type RegenerateBusinessObjectsReq struct {
	Id string `path:"id" validate:"required"`
}

type RegenerateBusinessObjectsResp struct {
	ObjectCount    int `json:"object_count"`
	AttributeCount int `json:"attribute_count"`
}

type SaveBusinessObjectsReq struct {
	Type string `json:"type" validate:"required,oneof=object attribute"`
	Id   string `json:"id" validate:"required"`
	Name string `json:"name" validate:"required,max=100"`
}

type SaveBusinessObjectsResp struct {
	Code int32 `json:"code"`
}

type SaveSemanticInfoFieldData struct {
	Id                *string `json:"id" validate:"required"`
	FieldBusinessName *string `json:"field_business_name" validate:"omitempty,max=255"`
	FieldRole         *int8   `json:"field_role" validate:"omitempty,min=1,max=8"`
	FieldDescription  *string `json:"field_description" validate:"omitempty,max=300"`
}

type SaveSemanticInfoReq struct {
	Id        string                        `path:"id" validate:"required"`
	TableData *SaveSemanticInfoTableData    `json:"tableData"`
	FieldData *SaveSemanticInfoFieldData    `json:"fieldData"`
}

type SaveSemanticInfoResp struct {
	Code int32 `json:"code"`
}

type SaveSemanticInfoTableData struct {
	Id                *string `json:"id" validate:"required"`
	TableBusinessName *string `json:"table_business_name" validate:"omitempty,max=255"`
	TableDescription  *string `json:"table_description" validate:"omitempty,max=300"`
}

type SubmitUnderstandingReq struct {
	Id string `path:"id" validate:"required"`
}

type SubmitUnderstandingResp struct {
	Success bool `json:"success"`
}

type BusinessObject struct {
	Id         string                    `json:"id"`
	ObjectName string                    `json:"object_name"`
	Attributes []BusinessObjectAttribute `json:"attributes"`
}

type BusinessObjectAttribute struct {
	Id                string  `json:"id"`
	AttrName          string  `json:"attr_name"`
	FormViewFieldId   string  `json:"form_view_field_id"`
	FieldTechName     string  `json:"field_tech_name"`
	FieldBusinessName *string `json:"field_business_name"`
	FieldRole         *int8   `json:"field_role"`
	FieldType         string  `json:"field_type"`
}
