// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type DeleteBusinessObjectsReq struct {
	Id string `path:"id" validate:"required"`
}

type DeleteBusinessObjectsResp struct {
	Success bool `json:"success"`
}

type GenerateUnderstandingReq struct {
	Id     string           `path:"id" validate:"required"`
	Fields []FieldSelection `json:"fields,omitempty"`
}

type GenerateUnderstandingResp struct {
	UnderstandStatus int8 `json:"understand_status"`
}

type GetBusinessObjectsReq struct {
	Id       string  `path:"id" validate:"required"`
	ObjectId *string `form:"object_id,optional"`
	Keyword  *string `form:"keyword,optional"`
}

type GetBusinessObjectsResp struct {
	List               []BusinessObject    `json:"list"`
	UnidentifiedFields []UnidentifiedField `json:"unidentified_fields,optional"`
}

type GetFieldsReq struct {
	Id             string  `path:"id" validate:"required"`
	Keyword        *string `form:"keyword,optional"`
	OnlyIncomplete *bool   `form:"only_incomplete,optional"`
}

type GetFieldsResp struct {
	CurrentVersion    int                 `json:"current_version"`
	TableBusinessName *string             `json:"table_business_name"`
	TableTechName     string              `json:"table_tech_name"`
	TableDescription  *string             `json:"table_description"`
	Fields            []FieldSemanticInfo `json:"fields"`
}

type GetStatusReq struct {
	Id string `path:"id" validate:"required"`
}

type GetStatusResp struct {
	UnderstandStatus int8 `json:"understand_status"`
}

type MoveAttributeReq struct {
	Id               string `path:"id" validate:"required"`
	AttributeId      string `json:"attribute_id" validate:"required"`
	TargetObjectUuid string `json:"target_object_uuid" validate:"required"`
}

type MoveAttributeResp struct {
	AttributeId      string `json:"attribute_id"`
	BusinessObjectId string `json:"business_object_id"`
}

type RegenerateBusinessObjectsReq struct {
	Id string `path:"id" validate:"required"`
}

type RegenerateBusinessObjectsResp struct {
	UnderstandStatus int8 `json:"understand_status"`
}

type SaveBusinessObjectsReq struct {
	Id       string `path:"id" validate:"required"`
	Type     string `json:"type" validate:"required,oneof=object attribute"`
	ObjectId string `json:"id" validate:"required"`
	Name     string `json:"name" validate:"required,max=100"`
}

type SaveBusinessObjectsResp struct {
	Code int32 `json:"code"`
}

type SaveSemanticInfoReq struct {
	Id        string                     `path:"id" validate:"required"`
	TableData *SaveSemanticInfoTableData `json:"tableData"`
	FieldData *SaveSemanticInfoFieldData `json:"fieldData"`
}

type SaveSemanticInfoResp struct {
	Code int32 `json:"code"`
}

type SubmitUnderstandingReq struct {
	Id string `path:"id" validate:"required"`
}

type SubmitUnderstandingResp struct {
	Success bool `json:"success"`
}
