// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BatchObjectMatchReq struct {
	Entries []SourceObject `json:"entries" validate:"required,min=1,max=100"`
	KnId    string         `json:"kn_id" validate:"required"` // 知识网络ID
	OtId    string         `json:"ot_id" validate:"required"` // 网络中指定对象ID
}

type BatchObjectMatchResp struct {
	Entries []MatchResult `json:"entries"` // 匹配结果列表
}

type DeleteBusinessObjectsReq struct {
	Id string `path:"id" validate:"required,uuid"`
}

type DeleteBusinessObjectsResp struct {
	Success bool `json:"success"`
}

type GenerateUnderstandingReq struct {
	Id     string           `path:"id" validate:"required,uuid"`
	Fields []FieldSelection `json:"fields,optional"`
}

type GenerateUnderstandingResp struct {
	UnderstandStatus int8 `json:"understand_status"`
}

type GetBusinessObjectsReq struct {
	Id       string  `path:"id" validate:"required,uuid"`
	ObjectId *string `form:"object_id,optional" validate:"omitempty,uuid"`
	Keyword  *string `form:"keyword,optional"`
}

type GetBusinessObjectsResp struct {
	List               []BusinessObject    `json:"list"`
	UnidentifiedFields []UnidentifiedField `json:"unidentified_fields,optional"`
}

type GetFieldsReq struct {
	Id             string  `path:"id" validate:"required,uuid"`
	Keyword        *string `form:"keyword,optional"`
	OnlyIncomplete *bool   `form:"only_incomplete,optional"`
}

type GetFieldsResp struct {
	TableInfoId       *string             `json:"table_info_id"`
	TableBusinessName *string             `json:"table_business_name"`
	TableTechName     string              `json:"table_tech_name"`
	TableDescription  *string             `json:"table_description"`
	Fields            []FieldSemanticInfo `json:"fields"`
}

type GetStatusReq struct {
	Id string `path:"id" validate:"required,uuid"`
}

type GetStatusResp struct {
	UnderstandStatus int8 `json:"understand_status"`
}

type MoveAttributeReq struct {
	Id               string `path:"id" validate:"required,uuid"`
	AttributeId      string `json:"attribute_id" validate:"required,uuid"`
	TargetObjectUuid string `json:"target_object_uuid" validate:"required,uuid"`
}

type MoveAttributeResp struct {
	AttributeId      string `json:"attribute_id"`
	BusinessObjectId string `json:"business_object_id"`
}

type RegenerateBusinessObjectsReq struct {
	Id string `path:"id" validate:"required,uuid"`
}

type RegenerateBusinessObjectsResp struct {
	UnderstandStatus int8 `json:"understand_status"`
}

type SaveBusinessObjectsReq struct {
	Id   string `path:"id" validate:"required,uuid"`
	Type string `json:"type" validate:"required,oneof=object attribute"`
	OpId string `json:"op_id" validate:"required,uuid"`
	Name string `json:"name" validate:"required,max=100"`
}

type SaveBusinessObjectsResp struct {
	Code int32 `json:"code"`
}

type SaveSemanticInfoReq struct {
	Id        string                     `path:"id" validate:"required,uuid"`
	TableData *SaveSemanticInfoTableData `json:"tableData,optional"`
	FieldData *SaveSemanticInfoFieldData `json:"fieldData,optional"`
}

type SaveSemanticInfoResp struct {
	Code int32 `json:"code"`
}

type SubmitUnderstandingReq struct {
	Id string `path:"id" validate:"required,uuid"`
}

type SubmitUnderstandingResp struct {
	Success bool `json:"success"`
}
