// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BusinessObject struct {
	Id         string                    `json:"id"`
	ObjectName string                    `json:"object_name"`
	Attributes []BusinessObjectAttribute `json:"attributes"`
}

type BusinessObjectAttribute struct {
	Id                string  `json:"id"`
	AttrName          string  `json:"attr_name"`
	FormViewFieldId   string  `json:"form_view_field_id"`
	FieldTechName     string  `json:"field_tech_name"`
	FieldBusinessName *string `json:"field_business_name"`
	FieldRole         *int8   `json:"field_role"`
	FieldType         string  `json:"field_type"`
	Description       *string `json:"description,optional"`
}

type EmptyResp struct {
}

type FieldSelection struct {
	FormViewFieldId   string  `json:"form_view_field_id" validate:"required"`
	FieldTechName     string  `json:"field_tech_name" validate:"required"`
	FieldType         string  `json:"field_type" validate:"required"`
	FieldBusinessName *string `json:"field_business_name,omitempty"`
	FieldRole         *int8   `json:"field_role,omitempty"`
	FieldDescription  *string `json:"field_description,omitempty"`
}

type FieldSemanticInfo struct {
	FormViewFieldId   string  `json:"form_view_field_id"`
	FieldBusinessName *string `json:"field_business_name"`
	FieldTechName     string  `json:"field_tech_name"`
	FieldType         string  `json:"field_type"`
	FieldRole         *int8   `json:"field_role"`
	FieldDescription  *string `json:"field_description"`
}

type HealthResp struct {
	Status string `json:"status"`
}

type IdReq struct {
	Id int64 `path:"id"`
}

type IdsReq struct {
	Ids []int64 `json:"ids"`
}

type KeywordInfo struct {
	Keyword string `form:"keyword,optional"` // 关键字查询
}

type PageBaseInfo struct {
	Offset int `form:"offset,default=1,range=[1:]"`     // 页码，默认1
	Limit  int `form:"limit,default=10,range=[0:2000]"` // 每页大小，默认10，0表示不分页
}

type PageInfo struct {
	PageBaseInfo
	Direction string `form:"direction,default=desc,options=asc|desc"`               // 排序方向：asc 正序，desc 倒序
	Sort      string `form:"sort,default=created_at,options=created_at|updated_at"` // 排序字段
}

type PageInfoWithKeyword struct {
	PageInfo
	KeywordInfo
}

type PageResp struct {
	Entries    interface{} `json:"entries"`     // 数据列表
	TotalCount int64       `json:"total_count"` // 总记录数
}

type SaveSemanticInfoFieldData struct {
	Id                *string `json:"id" validate:"required"` // t_form_view_field_info_temp.id，用于 upsert 操作
	FieldBusinessName *string `json:"field_business_name" validate:"omitempty,max=255"`
	FieldRole         *int8   `json:"field_role" validate:"omitempty,min=1,max=8"`
	FieldDescription  *string `json:"field_description" validate:"omitempty,max=300"`
}

type SaveSemanticInfoTableData struct {
	Id                *string `json:"id" validate:"required"` // t_form_view_info_temp.id，用于 upsert 操作
	TableBusinessName *string `json:"table_business_name" validate:"omitempty,max=255"`
	TableDescription  *string `json:"table_description" validate:"omitempty,max=300"`
}

type UnidentifiedField struct {
	Id            string  `json:"id"`
	TechnicalName string  `json:"technical_name"`
	DataType      string  `json:"data_type"`
	BusinessName  *string `json:"business_name,optional"`
	FieldRole     *int8   `json:"field_role,optional"`
	Description   *string `json:"description,optional"`
}
