// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	data_semantic "github.com/kweaver-ai/dsg/services/apps/data-semantic/api/internal/handler/data_semantic"
	"github.com/kweaver-ai/dsg/services/apps/data-semantic/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthCheckHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 一键生成理解数据
				Method:  http.MethodPost,
				Path:    "/:id/generate",
				Handler: data_semantic.GenerateUnderstandingHandler(serverCtx),
			},
			{
				// 查询库表理解状态
				Method:  http.MethodGet,
				Path:    "/:id/status",
				Handler: data_semantic.GetStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/data-semantic"),
	)
}
