apiVersion: v1
name: data-semantic
description: A Helm chart for data-semantic services
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - semantic
  - data-understanding
maintainers:
  - name: "Data Semantic Team"
    email: "team@example.com"
