namespace: anyshare
replicaCount: 1

labels:
  deployment:
    name: data-semantic-deployment
  pod:
    app: data-semantic-pod
  service:
    app: data-semantic-service
  api:
    deployment:
      app: data-semantic-api
      component: api
    pod:
      app: data-semantic-api
      component: api
    service:
      app: data-semantic-api
  consumer:
    deployment:
      app: data-semantic-consumer
      component: consumer
    pod:
      app: data-semantic-consumer
      component: consumer

name: data-semantic-deployment

image:
  registry: acr.xxx.cn
  repository: af/data-semantic
  tag: "1.0.0-develop"
  pullPolicy: IfNotPresent

nodeSelector: []

service:
  name: data-semantic
  type: ClusterIP
  port: 8888
  telemetry:
    log:
      enabled: false
      endpoint: http://feed-ingester-service:13031/api/feed_ingester/v1/jobs/job-log/events
      level: info
    trace:
      enabled: false
      endpoint: http://feed-ingester-service:13031/api/feed_ingester/v1/jobs/job-trace/events

ports:
  name: server-port
  containerPort: 8888

depServices:
  class-443:
    ingressClass: class-443
  rds:
    admin_key: ''
    host: mariadb-mariadb-master.resource.svc.cluster.local
    hostRead: 'mariadb-mariadb-master.resource.svc.cluster.local'
    port: 3330
    portRead: 3330
    source_type: internal
    type: MariaDB
    user: 'anyshare'
    password: ''
    database: 'af_main'
  hydra:
    administrativeHost: hydra-admin
    administrativePort: 4445
  user-management:
    privateHost: user-management-private
    privatePort: 30980
  af-sailor-service:
    protocol: http
    host: af-sailor-agent
    port: 9595
  mq:
    auth:
      mechanism: 'PLAIN'
      username: 'kafkaclient'
      password: ''
    mqHost: 'kafka-headless.resource'
    mqLookupdHost: ""
    mqLookupdPort: 0
    mqPort: 9097
    mqType: kafka
  redis:
    connectInfo:
      masterGroupName: mymaster
      password: ''
      sentinelHost: proton-redis-proton-redis-sentinel.resource.svc.cluster.local
      sentinelPassword: ''
      sentinelPort: 26379
      sentinelUsername: root
      username: root
    connectType: sentinel
    sourceType: internal
    database: 0

resources:
  requests:
    cpu: 0.1
    memory: 100Mi
  limits:
    cpu: 500m
    memory: 1024Mi

consumer:
  enabled: true
  name: data-semantic-consumer
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
