apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-semantic.fullname" . }}-consumer
  namespace: {{ include "data-semantic.namespace" . }}
  labels:
    {{- include "data-semantic.labels" . | nindent 4 }}
data:
  consumer.yaml: |
    Name: data-semantic-consumer
    Mode: console

    Log:
      ServiceName: data-semantic-consumer
      Mode: console
      Level: info

    Telemetry:
      Name: data-semantic-consumer
      Endpoint: ""
      Sampler: 1.0
      Batcher: jaeger

    MQ:
      Type: kafka
      Kafka:
        Brokers:
          - kafka-headless.resource:9097
        Topic: data-understanding-responses
        Group: data-semantic-consumer-group
        Username: kafkaclient
        Password: eisoo.com123
      Redis:
        Host: proton-redis-proton-redis-sentinel.resource.svc.cluster.local.
        Port: 26379
        Password: eisoo.com123
        Channel: messages

    DB:
      Default:
        Host: mariadb-mariadb-master.resource.svc.cluster.local.
        Port: 3330
        Database: af_main
        Username: anyshare
        Password: eisoo.com123
        Charset: utf8mb4
        MaxIdleConns: 10
        MaxOpenConns: 100
        ConnMaxLifetime: 3600
        LogLevel: warn
        SlowThreshold: 200

    Cache:
      - Host: proton-redis-proton-redis-sentinel.resource.svc.cluster.local.
        Type: node
