apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name.api }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels.api.deployment | nindent 4}}
spec:
  replicas: {{ .Values.api.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels.api.pod | nindent 6}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-api.yaml") . | sha256sum }}
      labels:
        {{- toYaml .Values.labels.api.pod | nindent 8}}
    spec:
      containers:
      - name: api
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8888
          protocol: TCP
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        resources:
          {{- toYaml .Values.api.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /app/etc
          readOnly: true
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: config
        configMap:
          name: {{ .Values.name.api }}-cm
      - name: logs
        emptyDir: {}
    {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- range .}}
        {{ .labelKey | quote }}: {{ .labelVal | quote }}
      {{- end }}
    {{- end }}
