apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.api.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{ toYaml .Values.labels.api.service | indent 4}}
spec:
  type: {{ .Values.service.api.type }}
  ports:
  - port: {{ .Values.service.api.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
{{toYaml .Values.labels.api.pod | indent 4}}
